name: signalr_netcore_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.11.0
  quiver: ^3.2.1
  web_socket_channel: ^2.4.3

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
